# Generated by Django 2.2.8 on 2020-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='address',
            field=models.CharField(default='8009 39th AVE NE', max_length=60),
        ),
        migrations.AddField(
            model_name='host',
            name='city',
            field=models.CharField(default='Seattle', max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='country',
            field=models.CharField(default='United States', max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='email',
            field=models.CharField(default='Nebrasa', max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(default='firstTab.txt', max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default='pass123', max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='phone_number',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AddField(
            model_name='host',
            name='state',
            field=models.CharField(default='Washington', max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='zip',
            field=models.IntegerField(default=98115),
        ),
    ]
