# Generated by Django 2.2.8 on 2020-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200319_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='name',
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default='Joseph', max_length=30),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default='Dulapp', max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='first_name',
            field=models.CharField(default='Joseph', max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='last_name',
            field=models.CharField(default='Dulapp', max_length=30),
        ),
    ]
