# Generated by Django 2.2.8 on 2020-03-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_host_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone_number',
            field=models.CharField(default=' ', max_length=35),
        ),
    ]
