# Generated by Django 2.2.8 on 2020-03-19 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import reservations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_auto_20200319_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(default=datetime.datetime(2020, 3, 19, 18, 1, 29, 368654, tzinfo=utc))),
                ('checkout_date', models.DateField(default=datetime.datetime(2020, 3, 19, 18, 1, 29, 368672, tzinfo=utc))),
                ('guest_count', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=200)),
                ('status', models.CharField(choices=[(reservations.models.ReservationStatus('Pending'), 'Pending'), (reservations.models.ReservationStatus('Reserved'), 'Reserved'), (reservations.models.ReservationStatus('Cancelled'), 'Cancelled'), (reservations.models.ReservationStatus('Awaiting'), 'Awaiting')], default=reservations.models.ReservationStatus('Awaiting'), max_length=10)),
                ('billing_address', models.CharField(max_length=150)),
                ('city', models.CharField(default='Detroit', max_length=200)),
                ('state', models.CharField(default='Michigan', max_length=20)),
                ('country', models.CharField(default='United States', max_length=30)),
                ('card_no', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
        ),
    ]
