# Generated by Django 2.2.8 on 2020-03-19 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 43, 44, 291587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 43, 44, 291604, tzinfo=utc)),
        ),
    ]
