# Generated by Django 2.2.8 on 2020-03-19 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200319_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 58, 20, 593240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 58, 20, 593258, tzinfo=utc)),
        ),
    ]
