# Generated by Django 2.2.8 on 2020-03-19 19:20

from django.db import migrations, models
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20200319_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[(reservations.models.ReservationStatus('Pending'), 'Pending'), (reservations.models.ReservationStatus('Reserved'), 'Reserved'), (reservations.models.ReservationStatus('Cancelled'), 'Cancelled'), (reservations.models.ReservationStatus('Awaiting'), 'Awaiting')], default=reservations.models.ReservationStatus('Awaiting'), max_length=30),
        ),
    ]
