# Generated by Django 2.2.8 on 2020-03-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20200319_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Vacant', max_length=15),
        ),
    ]
