# Generated by Django 2.2.8 on 2020-03-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200323_0427'),
        ('reservations', '0010_auto_20200322_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Guest'),
        ),
    ]
