# Generated by Django 2.2.8 on 2020-03-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.CharField(max_length=150)),
                ('city', models.CharField(default='Detroit', max_length=200)),
                ('state', models.CharField(default='Michigan', max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Host')),
            ],
        ),
        migrations.CreateModel(
            name='GuestPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.CharField(max_length=150)),
                ('city', models.CharField(default='Detroit', max_length=200)),
                ('state', models.CharField(default='Michigan', max_length=20)),
                ('country', models.CharField(default='United States', max_length=30)),
                ('card_no', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Guest')),
            ],
        ),
    ]
