# Generated by Django 2.2.8 on 2020-03-19 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Room1', max_length=30)),
                ('address', models.CharField(default='8 mile', max_length=30)),
                ('city', models.CharField(default='Detroit', max_length=40)),
                ('state', models.CharField(default='Michigan', max_length=30)),
                ('country', models.CharField(default='UnitedStates', max_length=30)),
                ('lat', models.FloatField(default=-98.0)),
                ('long', models.FloatField(default=40.0)),
                ('property_type', models.CharField(default='1 BR appartment', max_length=50)),
                ('guest_count', models.IntegerField(default=1)),
                ('bed_count', models.IntegerField(default=1)),
                ('bath_count', models.IntegerField(default=1)),
                ('description', models.CharField(default='No description', max_length=500)),
                ('available_date', models.DateField(default=datetime.datetime(2020, 3, 19, 18, 0, 58, 512754, tzinfo=utc))),
                ('auto_approve', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=300)),
                ('published', models.DateField(default=datetime.datetime(2020, 3, 19, 18, 0, 58, 512789))),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Host')),
            ],
        ),
    ]
