# Generated by Django 2.2.8 on 2020-03-19 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 1, 29, 368025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 1, 29, 368061)),
        ),
    ]
