# Generated by Django 2.2.8 on 2020-03-19 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200319_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 43, 44, 290992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 43, 44, 291025)),
        ),
    ]
