# Generated by Django 2.2.8 on 2020-03-19 18:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200319_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 51, 37, 40645)),
        ),
    ]
