# Generated by Django 2.2.8 on 2020-03-19 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200319_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='room',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 18, 59, 43, 26811)),
        ),
    ]
