# Generated by Django 2.2.8 on 2020-03-19 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200319_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='published',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
