# Generated by Django 2.2.8 on 2020-03-23 20:50

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_reserved_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reserved_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=list), default=list, size=None),
        ),
    ]
